### ISSUE TITLE
Villager Visual Glitch 1.20.2

### ISSUE THREAD

**Issue by droppedmycroissant** [DansDatapacks/PlushPets#1]
In 1.20.2, the villagers on the plush pets are visible when I walk up to them. 
![Visual Villager Glitch](https://github.com/DansDatapacks/PlushPets/assets/63214460/2128b0d5-6a8a-43a7-9694-591107af2075)

**Comment by Gottor** [comment]
Same bug on purpurmc_1-20-2_2082..

**Comment by Dan-Mizu** [comment]
Yes this glitch has been a thing on non-vanilla server jars. They do not adhere to vanilla minecraft commands as tight as datapacks need them- so they have issues with almost all datapacks.

**Comment by droppedmycroissant** [comment]
> Yes this glitch has been a thing on non-vanilla server jars. They do not adhere to vanilla minecraft commands as tight as datapacks need them- so they have issues with almost all datapacks.

I’m having this issue on Minecraft Realms on vanilla Minecraft.

**Comment by Dan-Mizu** [comment]
> > Yes this glitch has been a thing on non-vanilla server jars. They do not adhere to vanilla minecraft commands as tight as datapacks need them- so they have issues with almost all datapacks.
> 
> I’m having this issue on Minecraft Realms on vanilla Minecraft.

What version of the datapack and vanilla minecraft are you running?

**Comment by droppedmycroissant** [comment]
> > > Yes this glitch has been a thing on non-vanilla server jars. They do not adhere to vanilla minecraft commands as tight as datapacks need them- so they have issues with almost all datapacks.
> > 
> > 
> > I’m having this issue on Minecraft Realms on vanilla Minecraft.
> 
> What version of the datapack and vanilla minecraft are you running?

I'm running v.1.3 on 1.20.2 vanilla Minecraft.

**Comment by Dan-Mizu** [comment]
fixed in individual release for 1.20.2.

sorry for taking so long to fix that. did not realize that 1.20.2 changes the tag for `ActiveEffects` to `active_effects`.

**Comment by droppedmycroissant** [comment]
> fixed in individual release for 1.20.2.
> 
> sorry for taking so long to fix that. did not realize that 1.20.2 changes the tag for `ActiveEffects` to `active_effects`.

no worries! my friend and I really love this datapack and are very excited to play around with it again. thanks for the fix!
